nodeLinker: node-modules

npmScopes:
  fortawesome:
    npmAlwaysAuth: true
    npmRegistryServer: "https://npm.fontawesome.com/"
    npmAuthToken: "2DD68B3B-EA83-4EB7-9889-66EBDD08E1D8"
  awesome.me:
    npmAlwaysAuth: true
    npmRegistryServer: "https://npm.fontawesome.com/"
    npmAuthToken: "2DD68B3B-EA83-4EB7-9889-66EBDD08E1D8"
