npmScopes:
  awesome.me:
    npmRegistryServer: "https://npm.fontawesome.com/"
  fortawesome:
    npmRegistryServer: "https://npm.fontawesome.com/"

npmRegistries:
  "https://npm.fontawesome.com/":
    npmAuthToken: "2DD68B3B-EA83-4EB7-9889-66EBDD08E1D8"
