npmScopes:
  awesome.me:
    npmRegistryServer: "https://npm.fontawesome.com/"
    npmAlwaysAuth: true
    npmAuthToken: "2DD68B3B-EA83-4EB7-9889-66EBDD08E1D8"
  fortawesome:
    npmRegistryServer: "https://npm.fontawesome.com/"
    npmAlwaysAuth: true
    npmAuthToken: "2DD68B3B-EA83-4EB7-9889-66EBDD08E1D8"
