name: Pull Request Checks

on:
  pull_request:
    branches: ["main"]

jobs:
  static:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js Runtime
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install deps
        run: npm install

      - name: Check formatting
        run: npm run format:check

      - name: Run static checks
        env:
          SKIP_ENV_VALIDATION: true
        # nextjs build does linting and type checking + checks imports and other nextjs specific things
        run: |
          npm run build
